package cn.nothinghere.factory.region;

import static cn.nothinghere.factory.region.Province.*;

/**
 * @author amos.chenj@outlook.com
 */
public enum City implements Region{
    /**
     * 四个直辖市
     */
    Beijing(Province.Beijing,"北京市"),
    Tianjin(Province.Tianjin,"天津市"),
    Shanghai(Province.Shanghai,"上海市"),
    Chongqing(Province.Chongqing,"重庆市"),

    Shijiazhuang(Hebei,"石家庄市"),
    Tangshan(Hebei,"唐山市"),
    Qinhuangdao(Hebei,"秦皇岛市"),
    Handan(Hebei,"邯郸市"),
    Xingtai(Hebei,"邢台市"),
    Baoding(Hebei,"保定市"),
    Zhangjiakou(Hebei,"张家口市"),
    Chengde(Hebei,"承德市"),
    Cangzhou(Hebei,"沧州市"),
    Langfang(Hebei,"廊坊市"),
    Hengshui(Hebei,"衡水市"),

    Taiyuan(Shanxi,"太原市"),
    Datong(Shanxi,"大同市"),
    Yangquan(Shanxi,"阳泉市"),
    Zhangzhi(Shanxi,"长治市"),
    Jincheng(Shanxi,"晋城市"),
    Shuozhou(Shanxi,"朔州市"),
    Jinzhong(Shanxi,"晋中市"),
    Yuncheng(Shanxi,"运城市"),
    Xinzhou(Shanxi,"忻州市"),
    Linfen(Shanxi,"临汾市"),
    Lvliang(Shanxi,"吕梁市"),

    Huhehaote(NeiMonggol,"呼和浩特市"),
    Baotou(NeiMonggol,"包头市"),
    Wuhai(NeiMonggol,"乌海市"),
    Chifeng(NeiMonggol,"赤峰市"),
    Tongliao(NeiMonggol,"通辽市"),
    Eerduosi(NeiMonggol,"鄂尔多斯市"),
    Hulunbeier(NeiMonggol,"呼伦贝尔市"),
    Bayannaoer(NeiMonggol,"巴彦淖尔市"),
    Wulanchabu(NeiMonggol,"乌兰察布市"),
    Xinganmeng(NeiMonggol,"兴安盟"),
    Xilinguolemeng(NeiMonggol,"锡林郭勒盟"),
    Alashanmeng(NeiMonggol,"阿拉善盟"),

    Shenyang(Liaoning,"沈阳市"),
    Dalian(Liaoning,"大连市"),
    Anshan(Liaoning,"鞍山市"),
    Fushun(Liaoning,"抚顺市"),
    Benxi(Liaoning,"本溪市"),
    Dandong(Liaoning,"丹东市"),
    Jinzhou(Liaoning,"锦州市"),
    Yingkou(Liaoning,"营口市"),
    Fuxin(Liaoning,"阜新市"),
    Liaoyang(Liaoning,"辽阳市"),
    Panjin(Liaoning,"盘锦市"),
    Tieling(Liaoning,"铁岭市"),
    Chaoyang(Liaoning,"朝阳市"),
    Huludao(Liaoning,"葫芦岛市"),

    Changchun(Jilin,"长春市"),
    /**
     * 吉林市和吉林省拼音会有冲突，所以在此加上city后缀以示区分
     */
    JilinCity(Jilin,"吉林市"),
    Siping(Jilin,"四平市"),
    Liaoyuan(Jilin,"辽源市"),
    Tonghua(Jilin,"通化市"),
    Baishan(Jilin,"白山市"),
    Songyuan(Jilin,"松原市"),
    Baicheng(Jilin,"白城市"),
    Yanbianchaoxianzu(Jilin,"延边朝鲜族自治州"),

    Haerbin(Heilongjiang,"哈尔滨市"),
    Qiqihaer(Heilongjiang,"齐齐哈尔市"),
    Jixi(Heilongjiang,"鸡西市"),
    Hegang(Heilongjiang,"鹤岗市"),
    Shuangyashan(Heilongjiang,"双鸭山市"),
    Daqing(Heilongjiang,"大庆市"),
    Yichun_HLJ(Heilongjiang,"伊春市"),
    Jiamusi(Heilongjiang,"佳木斯市"),
    Qitaihe(Heilongjiang,"七台河市"),
    Mudanjiang(Heilongjiang,"牡丹江市"),
    Heihe(Heilongjiang,"黑河市"),
    Suihua(Heilongjiang,"绥化市"),
    Daxinganling(Heilongjiang,"大兴安岭地区"),

    Nanjing(Jiangsu,"南京市"),
    Wuxi(Jiangsu,"无锡市"),
    Xuzhou(Jiangsu,"徐州市"),
    Changzhou(Jiangsu,"常州市"),
    Suzhou_SJ(Jiangsu,"苏州市"),
    Nantong(Jiangsu,"南通市"),
    Lianyungang(Jiangsu,"连云港市"),
    Huaian(Jiangsu,"淮安市"),
    Yancheng(Jiangsu,"盐城市"),
    Yangzhou(Jiangsu,"扬州市"),
    Zhenjiang(Jiangsu,"镇江市"),
    Taizhou_JS(Jiangsu,"泰州市"),
    Suqian(Jiangsu,"宿迁市"),

    Hangzhou(Zhejiang,"杭州市"),
    Ningbo(Zhejiang,"宁波市"),
    Wenzhou(Zhejiang,"温州市"),
    Jiaxing(Zhejiang,"嘉兴市"),
    Huzhou(Zhejiang,"湖州市"),
    Shaoxing(Zhejiang,"绍兴市"),
    Jinhua(Zhejiang,"金华市"),
    Quzhou(Zhejiang,"衢州市"),
    Zhoushan(Zhejiang,"舟山市"),
    Taizhou_ZJ(Zhejiang,"台州市"),
    Lishui(Zhejiang,"丽水市"),

    Hefei(Anhui,"合肥市"),
    Wuhu(Anhui,"芜湖市"),
    Bangbu(Anhui,"蚌埠市"),
    Huainan(Anhui,"淮南市"),
    Maanshan(Anhui,"马鞍山市"),
    Huaibei(Anhui,"淮北市"),
    Tongling(Anhui,"铜陵市"),
    Anqing(Anhui,"安庆市"),
    Huangshan(Anhui,"黄山市"),
    Chuzhou(Anhui,"滁州市"),
    Fuyang(Anhui,"阜阳市"),
    Suzhou_AH(Anhui,"宿州市"),
    Liuan(Anhui,"六安市"),
    Bozhou(Anhui,"亳州市"),
    Chizhou(Anhui,"池州市"),
    Xuancheng(Anhui,"宣城市"),

    Fuzhou_FJ(Fujian,"福州市"),
    Shamen(Fujian,"厦门市"),
    Putian(Fujian,"莆田市"),
    Sanming(Fujian,"三明市"),
    Quanzhou(Fujian,"泉州市"),
    Zhangzhou(Fujian,"漳州市"),
    Nanping(Fujian,"南平市"),
    Longyan(Fujian,"龙岩市"),
    Ningde(Fujian,"宁德市"),

    Nanchang(Jiangxi,"南昌市"),
    Jingdezhen(Jiangxi,"景德镇市"),
    Pingxiang(Jiangxi,"萍乡市"),
    Jiujiang(Jiangxi,"九江市"),
    Xinyu(Jiangxi,"新余市"),
    Yingtan(Jiangxi,"鹰潭市"),
    Ganzhou(Jiangxi,"赣州市"),
    Jian(Jiangxi,"吉安市"),
    Yichun_JX(Jiangxi,"宜春市"),
    Fuzhou_JX(Jiangxi,"抚州市"),
    Shangrao(Jiangxi,"上饶市"),

    Jinan(Shandong,"济南市"),
    Qingdao(Shandong,"青岛市"),
    Zibo(Shandong,"淄博市"),
    Zaozhuang(Shandong,"枣庄市"),
    Dongying(Shandong,"东营市"),
    Yantai(Shandong,"烟台市"),
    Weifang(Shandong,"潍坊市"),
    Jining(Shandong,"济宁市"),
    Taian(Shandong,"泰安市"),
    Weihai(Shandong,"威海市"),
    Rizhao(Shandong,"日照市"),
    Laiwu(Shandong,"莱芜市"),
    Linyi(Shandong,"临沂市"),
    Dezhou(Shandong,"德州市"),
    Liaocheng(Shandong,"聊城市"),
    Binzhou(Shandong,"滨州市"),
    Heze(Shandong,"菏泽市"),

    Zhengzhou(Henan,"郑州市"),
    Kaifeng(Henan,"开封市"),
    Luoyang(Henan,"洛阳市"),
    Pingdingshan(Henan,"平顶山市"),
    Anyang(Henan,"安阳市"),
    Hebi(Henan,"鹤壁市"),
    Xinxiang(Henan,"新乡市"),
    Jiaozuo(Henan,"焦作市"),
    Jiyuan(Henan,"济源市"),
    Puyang(Henan,"濮阳市"),
    Xuchang(Henan,"许昌市"),
    Luohe(Henan,"漯河市"),
    Sanmenxia(Henan,"三门峡市"),
    Nanyang(Henan,"南阳市"),
    Shangqiu(Henan,"商丘市"),
    Xinyang(Henan,"信阳市"),
    Zhoukou(Henan,"周口市"),
    Zhumadian(Henan,"驻马店市"),

    Wuhan(Hubei,"武汉市"),
    Huangshi(Hubei,"黄石市"),
    Shiyan(Hubei,"十堰市"),
    Yichang(Hubei,"宜昌市"),
    Xiangyang(Hubei,"襄阳市"),
    Ezhou(Hubei,"鄂州市"),
    Jingmen(Hubei,"荆门市"),
    Xiaogan(Hubei,"孝感市"),
    Jingzhou(Hubei,"荆州市"),
    Huanggang(Hubei,"黄冈市"),
    Xianning(Hubei,"咸宁市"),
    Suizhou(Hubei,"随州市"),
    Enshitujiazumiaozu(Hubei,"恩施土家族苗族自治州"),
    Xiantao(Hubei,"仙桃市"),
    Qianjiang(Hubei,"潜江市"),
    Tianmen(Hubei,"天门市"),
    Shennongjialinqu(Hubei,"神农架林区"),

    Changsha(Hunan,"长沙市"),
    Zhuzhou(Hunan,"株洲市"),
    Xiangtan(Hunan,"湘潭市"),
    Hengyang(Hunan,"衡阳市"),
    Shaoyang(Hunan,"邵阳市"),
    Yueyang(Hunan,"岳阳市"),
    Changde(Hunan,"常德市"),
    Zhangjiajie(Hunan,"张家界市"),
    Yiyang(Hunan,"益阳市"),
    Chenzhou(Hunan,"郴州市"),
    Yongzhou(Hunan,"永州市"),
    Huaihua(Hunan,"怀化市"),
    Loudi(Hunan,"娄底市"),
    Xiangxitujiazumiaozu(Hunan,"湘西土家族苗族自治州"),

    Guangzhou(Guangdong,"广州市"),
    Shaoguan(Guangdong,"韶关市"),
    Shenzhen(Guangdong,"深圳市"),
    Zhuhai(Guangdong,"珠海市"),
    Shantou(Guangdong,"汕头市"),
    Foshan(Guangdong,"佛山市"),
    Jiangmen(Guangdong,"江门市"),
    Zhanjiang(Guangdong,"湛江市"),
    Maoming(Guangdong,"茂名市"),
    Zhaoqing(Guangdong,"肇庆市"),
    Huizhou(Guangdong,"惠州市"),
    Meizhou(Guangdong,"梅州市"),
    Shanwei(Guangdong,"汕尾市"),
    Heyuan(Guangdong,"河源市"),
    Yangjiang(Guangdong,"阳江市"),
    Qingyuan(Guangdong,"清远市"),
    Dongguan(Guangdong,"东莞市"),
    Zhongshan(Guangdong,"中山市"),
    Dongshaqundao(Guangdong,"东沙群岛"),
    Chaozhou(Guangdong,"潮州市"),
    Jieyang(Guangdong,"揭阳市"),
    Yunfu(Guangdong,"云浮市"),

    Nanning(Guangxi,"南宁市"),
    Liuzhou(Guangxi,"柳州市"),
    Guilin(Guangxi,"桂林市"),
    Wuzhou(Guangxi,"梧州市"),
    Beihai(Guangxi,"北海市"),
    Fangchenggang(Guangxi,"防城港市"),
    Qinzhou(Guangxi,"钦州市"),
    Guigang(Guangxi,"贵港市"),
    Yulin_GX(Guangxi,"玉林市"),
    Baise(Guangxi,"百色市"),
    Hezhou(Guangxi,"贺州市"),
    Hechi(Guangxi,"河池市"),
    Laibin(Guangxi,"来宾市"),
    Chongzuo(Guangxi,"崇左市"),

    Haikou(Hainan,"海口市"),
    Sanya(Hainan,"三亚市"),
    Sansha(Hainan,"三沙市"),
    Wuzhishan(Hainan,"五指山市"),
    Qionghai(Hainan,"琼海市"),
    Danzhou(Hainan,"儋州市"),
    Wenchang(Hainan,"文昌市"),
    Wanning(Hainan,"万宁市"),
    Dongfang(Hainan,"东方市"),
    Dinganxian(Hainan,"定安县"),
    Tunchangxian(Hainan,"屯昌县"),
    Chengmaixian(Hainan,"澄迈县"),
    Lingaoxian(Hainan,"临高县"),
    Baishalizu(Hainan,"白沙黎族自治县"),
    Changjianglizu(Hainan,"昌江黎族自治县"),
    Ledonglizu(Hainan,"乐东黎族自治县"),
    Lingshuilizu(Hainan,"陵水黎族自治县"),
    Baotinglizumiaozu(Hainan,"保亭黎族苗族自治县"),
    Qiongzhonglizumiaozu(Hainan,"琼中黎族苗族自治县"),
    Xishaqundao(Hainan,"西沙群岛"),
    Nanshaqundao(Hainan,"南沙群岛"),
    Zhongshaqundao(Hainan,"中沙群岛的岛礁及其海域"),

    Chengdou(Sichuan,"成都市"),
    Zigong(Sichuan,"自贡市"),
    Panzhihua(Sichuan,"攀枝花市"),
    Luzhou(Sichuan,"泸州市"),
    Deyang(Sichuan,"德阳市"),
    Mianyang(Sichuan,"绵阳市"),
    Guangyuan(Sichuan,"广元市"),
    Suining(Sichuan,"遂宁市"),
    Neijiang(Sichuan,"内江市"),
    Leshan(Sichuan,"乐山市"),
    Nanchong(Sichuan,"南充市"),
    Meishan(Sichuan,"眉山市"),
    Yibin(Sichuan,"宜宾市"),
    Guangan(Sichuan,"广安市"),
    Dazhou(Sichuan,"达州市"),
    Yaan(Sichuan,"雅安市"),
    Bazhong(Sichuan,"巴中市"),
    Ziyang(Sichuan,"资阳市"),
    Abazangzuqiangzu(Sichuan,"阿坝藏族羌族自治州"),
    Ganzizangzu(Sichuan,"甘孜藏族自治州"),
    Liangshanyizu(Sichuan,"凉山彝族自治州"),

    Guiyang(Guizhou,"贵阳市"),
    Liupanshui(Guizhou,"六盘水市"),
    Zunyi(Guizhou,"遵义市"),
    Anshun(Guizhou,"安顺市"),
    Tongren(Guizhou,"铜仁市"),
    Qianxinanbuyizumiaozu(Guizhou,"黔西南布依族苗族自治州"),
    Bijie(Guizhou,"毕节市"),
    Qiandongnanmiaozudongzu(Guizhou,"黔东南苗族侗族自治州"),
    Qiannanbuyizumiaozu(Guizhou,"黔南布依族苗族自治州"),

    Kunming(Yunnan,"昆明市"),
    Qujing(Yunnan,"曲靖市"),
    Yuxi(Yunnan,"玉溪市"),
    Baoshan(Yunnan,"保山市"),
    Zhaotong(Yunnan,"昭通市"),
    Lijiang(Yunnan,"丽江市"),
    Puer(Yunnan,"普洱市"),
    Lincang(Yunnan,"临沧市"),
    Chuxiongyizu(Yunnan,"楚雄彝族自治州"),
    Honghehanizuyizu(Yunnan,"红河哈尼族彝族自治州"),
    Wenshanzhuangzumiaozu(Yunnan,"文山壮族苗族自治州"),
    Xishuangbannadaizu(Yunnan,"西双版纳傣族自治州"),
    Dalibaizu(Yunnan,"大理白族自治州"),
    Dehongdaizujingpozu(Yunnan,"德宏傣族景颇族自治州"),
    Nujianglisuzu(Yunnan,"怒江傈僳族自治州"),
    Diqingzangzu(Yunnan,"迪庆藏族自治州"),

    Lasa(Xizang,"拉萨市"),
    Changdou(Xizang,"昌都市"),
    Shannan(Xizang,"山南市"),
    Rikaze(Xizang,"日喀则市"),
    Neiqu(Xizang,"那曲市"),
    Ali(Xizang,"阿里地区"),
    Linzhi(Xizang,"林芝市"),

    Xian(Shaanxi,"西安市"),
    Tongchuan(Shaanxi,"铜川市"),
    Baoji(Shaanxi,"宝鸡市"),
    Xianyang(Shaanxi,"咸阳市"),
    Weinan(Shaanxi,"渭南市"),
    Yanan(Shaanxi,"延安市"),
    Hanzhong(Shaanxi,"汉中市"),
    Yulin_SX(Shaanxi,"榆林市"),
    Ankang(Shaanxi,"安康市"),
    Shangluo(Shaanxi,"商洛市"),

    Lanzhou(Gansu,"兰州市"),
    Jiayuguan(Gansu,"嘉峪关市"),
    Jinchang(Gansu,"金昌市"),
    Baiyin(Gansu,"白银市"),
    Tianshui(Gansu,"天水市"),
    Wuwei(Gansu,"武威市"),
    Zhangye(Gansu,"张掖市"),
    Pingliang(Gansu,"平凉市"),
    Jiuquan(Gansu,"酒泉市"),
    Qingyang(Gansu,"庆阳市"),
    Dingxi(Gansu,"定西市"),
    Longnan(Gansu,"陇南市"),
    Linxiahuizu(Gansu,"临夏回族自治州"),
    Gannanzangzu(Gansu,"甘南藏族自治州"),

    Xining(Qinghai,"西宁市"),
    Haidong(Qinghai,"海东市"),
    Haibeizangzu(Qinghai,"海北藏族自治州"),
    Huangnanzangzu(Qinghai,"黄南藏族自治州"),
    Hainanzangzu(Qinghai,"海南藏族自治州"),
    Guoluozangzu(Qinghai,"果洛藏族自治州"),
    Yushuzangzu(Qinghai,"玉树藏族自治州"),
    Haiximengguzuzangzu(Qinghai,"海西蒙古族藏族自治州"),

    Yinchuan(Ningxia,"银川市"),
    Shizuishan(Ningxia,"石嘴山市"),
    Wuzhong(Ningxia,"吴忠市"),
    Guyuan(Ningxia,"固原市"),
    Zhongwei(Ningxia,"中卫市"),

    Wulumuqi(Xinjiang,"乌鲁木齐市"),
    Kelamayi(Xinjiang,"克拉玛依市"),
    Tulufan(Xinjiang,"吐鲁番市"),
    Hami(Xinjiang,"哈密市"),
    Changjihuizu(Xinjiang,"昌吉回族自治州"),
    Boertalamenggu(Xinjiang,"博尔塔拉蒙古自治州"),
    Bayinguolengmenggu(Xinjiang,"巴音郭楞蒙古自治州"),
    Akesu(Xinjiang,"阿克苏地区"),
    Kezilesukeerkezi(Xinjiang,"克孜勒苏柯尔克孜自治州"),
    Kashen(Xinjiang,"喀什地区"),
    Hetian(Xinjiang,"和田地区"),
    Yilihasake(Xinjiang,"伊犁哈萨克自治州"),
    Tacheng(Xinjiang,"塔城地区"),
    Aletai(Xinjiang,"阿勒泰地区"),
    Kekedala(Xinjiang,"可克达拉市"),
    Shihezi(Xinjiang,"石河子市"),
    Alaer(Xinjiang,"阿拉尔市"),
    Tumushuke(Xinjiang,"图木舒克市"),
    Wujiaqu(Xinjiang,"五家渠市"),
    Beitun(Xinjiang,"北屯市"),
    Tiemenguan(Xinjiang,"铁门关市"),
    Shuanghe(Xinjiang,"双河市"),
    Kunyu(Xinjiang,"昆玉市"),

    Taibei(Taiwan,"台北市"),
    Gaoxiong(Taiwan,"高雄市"),
    Tainan(Taiwan,"台南市"),
    Taizhong(Taiwan,"台中市"),
    Jinmenxian(Taiwan,"金门县"),
    Nantouxian(Taiwan,"南投县"),
    Jilong(Taiwan,"基隆市"),
    Xinzhu(Taiwan,"新竹市"),
    Jiayi(Taiwan,"嘉义市"),
    Xinbei(Taiwan,"新北市"),
    Yilanxian(Taiwan,"宜兰县"),
    Xinzhuxian(Taiwan,"新竹县"),
    Taoyuan(Taiwan,"桃园市"),
    Miaolixian(Taiwan,"苗栗县"),
    Zhanghuaxian(Taiwan,"彰化县"),
    Jiayixian(Taiwan,"嘉义县"),
    Yunlinxian(Taiwan,"云林县"),
    Pingdongxian(Taiwan,"屏东县"),
    Taidongxian(Taiwan,"台东县"),
    Hualianxian(Taiwan,"花莲县"),
    Penghuxian(Taiwan,"澎湖县"),
    Lianjiangxian(Taiwan,"连江县"),

    HongKongIsland(HongKong,"香港岛"),
    KowloonPeninsula(HongKong,"九龙"),
    NewTerritories(HongKong,"新界"),

    PeninsulaOfMacao(Macao,"澳门半岛"),
    Lidao(Macao,"离岛"),
    ;
    private Province parent;
    private String name;

    City(Province parent, String name) {
        this.parent = parent;
        this.name = name;
    }

    public String getName() {
        return name;
    }
}
